import { Footer } from "../components/footer/Footer";
import Navbar from "../components/Navbar/Navbar";
import "../styles/globals.css";

export const metadata = {
  title: "GitPeek - GitHub Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body cz-shortcut-listen="true">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
