import "../styles/globals.css";

export const metadata = {
  title: "GitPeek - GitHub Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body cz-shortcut-listen="true">{children}</body>
    </html>
  );
}
